### ISSUE TITLE
dupe in fixing butler and clinton ORIs 

### ISSUE THREAD

**Issue by brooke-watson** [jacobkap/crime_data#1]
Hey Jacob, 

This is a tremendous resource that you've put online! Both your data outputs and this code has  been incredibly helpful in my work—thanks so much for open sourcing it. 

I stumbled across the weirdness of the PAPEP00 ori in trying to do some county-level aggregation, which led me to lines 133-139 of `R/crosswalk.R`. I think in the code below you're attempting to fix Butler's variables twice, rather than fixing Butler and then fixing Clinton. 

```
  # Fix issue where Butler University has wrong county FIPS code
  crosswalk$fips_state_code[crosswalk$ori        == "IN04940"] <- "18"
  crosswalk$fips_county_code[crosswalk$ori       == "IN04940"] <- "097"
  crosswalk$fips_state_county_code[crosswalk$ori == "IN04940"] <- "18097"
  crosswalk$fips_place_code[crosswalk$ori        == "IN04940"] <- "36003"

  # Fix issue where Clinton Tennessee has wrong county FIPS code
  crosswalk$fips_state_code[crosswalk$ori        == "IN04940"] <- "47"
  crosswalk$fips_county_code[crosswalk$ori       == "IN04940"] <- "001"
  crosswalk$fips_state_county_code[crosswalk$ori == "IN04940"] <- "47001"
  crosswalk$fips_place_code[crosswalk$ori        == "IN04940"] <- "15580"
```

You also later filter out IN04940, so this bit ends up not mattering, but wanted to call this out in case this isn't the desired behavior, if/when you need to reproduce. (I wasn't certain about clinton's ORI, or else I would've submitted a PR).

Hope this helps, & thanks again!

**Comment by jacobkap** [comment]
Great catch, thank you! Code is fixed.
